# Generated by Django 2.2.1 on 2019-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_de_venda', models.CharField(max_length=75)),
                ('contato', models.CharField(max_length=20)),
                ('apostador', models.CharField(max_length=75)),
                ('numeros', models.CharField(max_length=40)),
            ],
        ),
    ]
